[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_NODE_ENV = "production"
  MISE_DISABLE = "true"  # Disable mise version manager
  NODE_VERSION = "18"    # Explicitly set Node version

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 