[build]
  command = "npm ci && npm install --save-dev typescript @types/react @types/node && npx tsc --init && npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_NODE_ENV = "production"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = true 